version: '4.8.1'
services:
    db:
        container_name: db
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_DATABASE: artichoke
            MYSQL_USER: admin
            MYSQL_PASSWORD: toor
        ports:
            - "9906:3306"
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./db:/var/lib/sql:rw
    flask:
        container_name: flask
        build: .
        depends_on:
            - db
        ports:
            - 6060:5000
        links:
            - "db"
        command: ["/bin/bash", "-c", "sleep 4;python ArtichokePlant.py"]
